<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer is correct' => 'Этот ответ правильный',
    'Mark answer as correct' => 'Пометить ответ как правильный',
    'Active' => 'Активные',
    'Oldest' => 'Старые',
    'Votes' => 'Голоса',
    'Add to favorite' => 'Добавить в избранное',
    'Answer' => 'Ответ',
    'Answer to {title}' => 'Ответ на {title}',
    'Ask a Question' => 'Задать вопрос',
    'Comma separated list of tags' => 'Список тегов через запятую',
    'Delete' => 'Удалить',
    'Draft' => 'Черновик',
    'Edit' => 'Редактировать',
    'Edit {title}' => 'Редактирование {title}',
    'Error create question' => 'Ошибка создания вопроса',
    'Error save question' => 'Ошибка сохранения вопроса',
    'Favorite' => 'Избранное',
    'Favorite Questions' => 'Избранные Вопросы',
    'Like' => 'Нравится',
    'Markdown powered content' => 'Поддерживается Markdown разметка',
    'My' => 'Мое',
    'No favorite questions' => 'Нет избранных вопросов',
    'No popular questions' => 'Нет популярных вопросов',
    'No questions yet' => 'Еще нет вопросов',
    'Popular Questions' => 'Популярные Вопросы',
    'Popular tags' => 'Популярные теги',
    'Publish' => 'Опубликовать',
    'Questions' => 'Вопросы',
    'Questions by tags' => 'Вопросы по тегам',
    'Sure?' => 'Уверены?',
    'The requested page does not exist.' => 'Вопрос не найден',
    'Update' => 'Обновить',
    'Vote down' => 'Голосовать против',
    'Vote up' => 'Голосовать за',
    'What\'s your question? Be specific.' => 'Каков ваш вопрос? Будьте точны.',
    'You are not allowed to perform this action.' => 'У вас нет доступа к этому действию.',
    'answers' => 'ответов',
    'views' => 'смотрело',
    'votes' => 'голосов',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '{n, plural, =0{Еще нет ответов} =1{Один ответ} other{# ответов}}',
];
