<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '' => '',
    'Draft' => '',
    'Markdown powered content' => '',
    'Publish' => '',
    'The requested page does not exist.' => '',
    'You are not allowed to perform this action.' => '',
    'Active' => 'Активные',
    'Add to favorite' => 'Добавить в избранное',
    'Ask a Question' => 'Задать вопрос',
    'Comma separated list of tags' => 'Список тегов через запятую',
    'Edit {title}' => 'Редактирование {title}',
    'Favorite' => 'Избранное',
    'Favorite Questions' => 'Избранные Вопросы',
    'My' => 'Мое',
    'No questions yet' => 'Еще нет вопросов',
    'Popular Questions' => 'Популярные Вопросы',
    'Popular tags' => 'Популярные теги',
    'Questions' => 'Вопросы',
    'Questions by tags' => 'Вопросы по тегам',
    'Sure?' => 'Уверены?',
    'Vote down' => 'Голосовать против',
    'Vote up' => 'Голосовать за',
    'answers' => 'ответов',
    'views' => 'смотрело',
    'votes' => 'голосов',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '{n, plural, =0{Еще нет ответов} =1{Один ответ} other{# ответов}}',
];
