<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer' => '',
    'Answer is correct' => '',
    'Answer to {title}' => '',
    'Delete' => '',
    'Edit' => '',
    'Error create question' => '',
    'Error save question' => '',
    'Like' => '',
    'Mark answer as correct' => '',
    'No favorite questions' => '',
    'No popular questions' => '',
    'Update' => '',
    'What\'s your question? Be specific.' => '',
    'Active' => 'Activo',
    'Add to favorite' => 'Agregar a favoritos',
    'Ask a Question' => 'Hacer una pregunta',
    'Comma separated list of tags' => 'Lista de etiquetas separadas por comas',
    'Draft' => 'Borrador',
    'Edit {title}' => 'Editar {title}',
    'Favorite' => 'Favoritos',
    'Favorite Questions' => 'Preguntas favoritas',
    'Markdown powered content' => 'Contenido potenciado por Markdown',
    'My' => 'Mis',
    'No questions yet' => 'Sin preguntas todavía',
    'Popular Questions' => 'Preguntas populares',
    'Popular tags' => 'Etiquetas populares',
    'Publish' => 'Publicar',
    'Questions' => 'Preguntas',
    'Questions by tags' => 'Preguntas por etiqueta',
    'Sure?' => '¿Seguro?',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Vote down' => 'Votar a favor',
    'Vote up' => 'Votar en contra',
    'You are not allowed to perform this action.' => 'No tiene permitido realizar esta acción.',
    'answers' => 'respuestas',
    'views' => 'vistas',
    'votes' => 'votos',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '{n, plural, =0{Sin respuestas todavía} =1{Una respuesta} other{# respuestas}}',
];
