<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Oldest' => '',
    'Votes' => '',
    'Add to favorite' => '',
    'Answer' => '',
    'Answer is correct' => '',
    'Answer to {title}' => '',
    'Ask a Question' => '',
    'Comma separated list of tags' => '',
    'Delete' => '',
    'Draft' => '',
    'Edit' => '',
    'Edit {title}' => '',
    'Error create question' => '',
    'Error save question' => '',
    'Favorite' => '',
    'Favorite Questions' => '',
    'Like' => '',
    'Mark answer as correct' => '',
    'Markdown powered content' => '',
    'My' => '',
    'No favorite questions' => '',
    'No popular questions' => '',
    'No questions yet' => '',
    'Popular Questions' => '',
    'Popular tags' => '',
    'Publish' => '',
    'Questions' => '',
    'Questions by tags' => '',
    'Sure?' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Vote down' => '',
    'Vote up' => '',
    'What\'s your question? Be specific.' => '',
    'You are not allowed to perform this action.' => '',
    'answers' => '',
    'views' => '',
    'votes' => '',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '',
];
